### ISSUE TITLE
Bug: Adjusting fan speed turns AC off

### ISSUE THREAD

**Issue by thatpaulallen** [nitaybz/homebridge-sensibo-ac#144]
When I adjust the fan speed the plugin switches the AC off

https://github.com/user-attachments/assets/44b9f854-a890-411f-ad67-5441eaee4dfc

**Comment by benwebbbenwebb** [comment]
Hi @thatpaulallen 

Looks like you’ve currently got the AC accessory (Auto, Cooling and Heat modes) grouped with the Fan and Dehumidifier accessories. For reasons (known only to Apple) they need Fan and Dehumidifier to be treated as separate units, rather than additional modes. What is currently happening is that you are turning Off the **_Cool mode_** and switching on/to the **_Fan mode_**.

My recommendation is to click the cog in the bottom right and then click “Show as Separate Tiles”. Once that’s done you should have individual buttons for each.

Then to change fan speed while cooling or heating (or auto) on the AC you’ll need to click the cog again (under the AC unit tile) and use the slider.

Again, not sure why Apple did it this way, but that’s what’s available in the Home app UI. Otherwise you could try using the Eve app.
