### ISSUE TITLE
Adding an option to use the fan speed as a light slider

### ISSUE THREAD

**Issue by JacobsonGal** [nitaybz/homebridge-sensibo-ac#152]
## Current Flow
In the current configuration, your can't change the fan speed from the iPhone control center, so if the iPhone is locked/not in the home app, you need to navigate to the home app, press on the ac accessory, open the settings and slide the fan slider.

## Requested Flow
Would be great of we could have a toggle to decide how to use the fan speed of the AC unit:
1. Regular fan slider from the accessory settings.
2. Fan slider: (that will be renders beneath the ac temp gauge)
 ![image](https://github.com/user-attachments/assets/af00742b-761f-4bd9-b946-ac23819736b6)
![image](https://github.com/user-attachments/assets/8b05dc04-6796-41df-a701-f50a13a32682)

Thanks you!

**Comment by benwebbbenwebb** [comment]
Hi @JacobsonGal 

I've also wanted something like this so keen to hear if you have any thoughts on how it might be achieved?

I think (at least in the current iOS v17 that I'm running) it's not possible due to Apple limitations on what is exposed in Control Centre...

The nearest workaround that I can think of is:
1. Go in to the Fan accessory from Control Centre, set the fan speed directly there
2. Wait a moment for the change to happen, then
3. Go in to the AC accessory and change the mode to Cool (or Heat, or Auto)
Note: this may require you to have the modes set as separate tiles

**Comment by ovq** [comment]
@benwebbbenwebb, maybe @JacobsonGal is running an iOS 18 beta, where you can expose specific HK devices / switches to Control Center...

**Comment by JacobsonGal** [comment]
@benwebbbenwebb There isn't any fan accessory, the fan slider is inside the AC settings, if there was a separate fan accessory, this issue would not have been needed.

**Comment by benwebbbenwebb** [comment]
Hi @JacobsonGal 

To confirm, the first image in your original comment isn't from your device?

My AC unit has separate modes (Fan only, Dry, Cool, Heat, Auto), Sensibo exposes these to this plugin and (depending on your settings in Homebridge and the Home app) this allows you to see separate accessories in the Home app, e.g.:
![Home_app](https://github.com/user-attachments/assets/479b5df4-83d7-4ec0-a36f-9661ba029a09)

This in turn means I can use the workaround I previously mentioned.

> The nearest workaround that I can think of is:
>
> 1. Go in to the Fan accessory from Control Centre, set the fan speed directly there
> 2. Wait a moment for the change to happen, then
> 3. Go in to the AC accessory and change the mode to Cool (or Heat, or Auto)
> Note: this may require you to have the modes set as separate tiles

Does your unit / Sensibo app not include a Fan mode?

As for your original suggestion, as I previously touched on, unfortunately due to the current Apple limitations I'm not aware of any way to bring the AC mode fan control in to Control Centre (without it being a separate accessory as advised above).

**Comment by JacobsonGal** [comment]
@nitaybz Hi Nitay!
Is there an option to use the fan accessory to be used in the regular modes as well?
![image](https://github.com/user-attachments/assets/6997996e-e38a-456f-9c03-cdaa9d3f56fa)

I want to use it like here, but when I'm setting the fan speed, the ac mode switch to FAN...
I want to stay on COLD mode and using the same switch for controlling the fan speed (instead the one in the accessory's settings.
![image](https://github.com/user-attachments/assets/1c894bcb-3d29-48cd-a0b1-13117aba5e61)

Is that optional? 
Thank you! 🙏

**Comment by benwebbbenwebb** [comment]
Hi @JacobsonGal 

Nitaybz isn’t really involved in the plugin anymore, but to answer your question (as I understand it) unfortunately no, the option you want is not possible.

Apple doesn’t allow modes other than AUTO or COOL or HEAT, in that mode selector under AC. This means that to support FAN mode a separate accessory is required.

I would recommend you explore the options within the Home app under the AC accessory and consider making the accessories (AC and FAN) appear as separate accessories in the Home app.

Setting FAN speed using that slider in your image is only for the FAN accessory and cannot be reconfigured for the AC.

It’s definitely not ideal but there isn’t any suitable option that I know of in the Home app.

You could take a look at the Eve app and see if that works better for your use case.
