### ISSUE TITLE
HAP Warning...

### ISSUE THREAD

**Issue by luissimoes** [nitaybz/homebridge-sensibo-ac#18]
Hi,
first: a BIG BIG thanks for your work!
Reporting this as I don't know if it is a real issue...?

When initialising homebridge this message comes in the Logs - and I have no idea what the Characteristic 00000010-0000-1000-8000-0026BB765291 is...

I switched the options in the UI and also manually in the config.json.... makes no difference

<<
_Initializing platform accessory 'Living Room AC'...
HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BC-0000-1000-8000-0026BB765291. Adding anyway.
[6/22/2020, 6:02:52 PM] Initializing platform accessory 'Office Luis AC'...
HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BC-0000-1000-8000-0026BB765291. Adding anyway.
[6/22/2020, 6:02:52 PM] Initializing platform accessory 'Sleeping room AC'...
HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BC-0000-1000-8000-0026BB765291. Adding anyway._
>>

**Comment by richsc** [comment]
I'm also getting this warning.

**Comment by nitaybz** [comment]
this is perfectly fine... no issue here...
I implemented "Current Relative Humidity" as part of the AC accessory and it just throw that warning but without affecting anything... in fact, Home app shows the "Current Relative Humidity" in the app perfectly fine:
<img width="414" alt="Screenshot 2020-06-23 at 10 56 52" src="https://user-images.githubusercontent.com/16838394/85376419-5b266a00-b540-11ea-9c38-ba9fc64784c5.png">

again, expected behaviour... so no issue here.
closing...
