### ISSUE TITLE
Sending on/off commands several times

### ISSUE THREAD

**Issue by dinhvh** [nitaybz/homebridge-sensibo-ac#34]
I hooked up switch to turn on & off my AC (or several of them).

Some of my AC will sometimes fail to get the command from the sensibo unit.
It would be cool if I could tap again on the switch if I found out that the AC didn't turn on or off properly.

Currently, it sounds like when the AC is already considered off, no addition command will be sent by the sensibo unit (via this homebridge plugin)

The following plugin does it:
https://github.com/noahfaust/homebridge-sensibo-sky

**Comment by nitaybz** [comment]
That's why I created the "AC Sync" button... it will change the state without sending another command to the AC, and then you can send the ON/OFF command again... my plugin is synced with the status in Sensibo so I don't see how it will be possible to send another command without changing the state first in Sensibo.

**Comment by dinhvh** [comment]
I'm using a fork with that change here:
https://github.com/dinhvh/homebridge-sensibo-ac/commit/dd686f95e675adb9dd21ce52b5138bd4c48ee554
And this change helps.

Maybe we could make it a setting?

**Comment by nitaybz** [comment]
done in the latest version... please verify and close when confirmed
