### ISSUE TITLE
Old Device Name is Picked Up Even Though Renamed in Sensibo

### ISSUE THREAD

**Issue by raeldor** [nitaybz/homebridge-sensibo-ac#47]
I renamed my device 'Living Room AC' on sensibo.  I could also rename in Homebridge, BUT when I click on the gear wheel for the device and scroll down there's a field called 'Name' that still says 'Office AC'.  Here's the even more odd thing.  It reflects the new name 'Living Room AC' in the front page of the Home app, but when I look at my SCENES, it has the OLD name 'Office AC'.  So now I'm really confused.

Why are there two names?  Why is the 'Office AC' still hanging around?  Where is this 'Name' field on the device settings that can't be edited coming from because there's not reference to 'Office AC' anymore in sensibo.  I tried removing and re-adding the device, but no luck.

**Comment by nitaybz** [comment]
that's because there are few services grouped together... so there is the name of the "master" accessory which holds all the services accessories which the ac is among them... what you see in scenes is the accessory within. it's easy to access it in 2 ways:
1. open the accessory from Home app and scroll down to settings, click on "accessories", there, you'll see the ac probably with the old name. you can then open the ac accessory within and change its name.
2. ** i prefer this method ** - open the accessory from Home app and scroll down to settings, click on "Show as separate tiles" to make the "master" accessory break into multiple separate accessories. you can always revert back from this method by clicking on any of the accessories and scrolling to settings clicking on "Show as a single tile".

Hope it solve your issue.

**Comment by raeldor** [comment]
That worked.  Thank you very much! Ray Sent from Mail for Windows 10 From: Nitay Ben-ZviSent: Wednesday, January 27, 2021 5:44 AMTo: nitaybz/homebridge-sensibo-acCc: Ray Price; AuthorSubject: Re: [nitaybz/homebridge-sensibo-ac] Old Device Name is Picked Up Even Though Renamed in Sensibo (#47) that's because there are few services grouped together... so there is the name of the "master" accessory which holds all the services accessories which the ac is among them... what you see in scenes is the accessory within. it's easy to access it in 2 ways:open the accessory from Home app and scroll down to settings, click on "accessories", there, you'll see the ac probably with the old name. you can then open the ac accessory within and change its name.** i prefer this method ** - open the accessory from Home app and scroll down to settings, click on "Show as separate tiles" to make the "master" accessory break into multiple separate accessories. you can always revert back from this method by clicking on any of the accessories and scrolling to settings clicking on "Show as a single tile".Hope it solve your issue.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
