### ISSUE TITLE
Cool mode (not auto)

### ISSUE THREAD

**Issue by fujitasenpai** [nitaybz/homebridge-sensibo-ac#62]
Is there a way to set the default mode "Cool" instead of Auto?

**Comment by nitaybz** [comment]
there is no default mode... it should take the last state when turning the ac on... I suggest you check if you used it in a scene or automation and the mode there is set to auto.

Please report back with more details of how you turned it on and in what situation you noticed it is switching to auto instead of the previous mode

**Comment by jsalva23** [comment]
> there is no default mode... it should take the last state when turning the ac on... I suggest you check if you used it in a scene or automation and the mode there is set to auto.
> 
> Please report back with more details of how you turned it on and in what situation you noticed it is switching to auto instead of the previous mode

ok I just tested and for me it has two different results depending on how I turn it on:

Scenario 1: I use the home app on my iPhone to turn the AC on, it will turn on to the last state no problem there, if it was on Cool the last time I used it will turn back on in cool status when I use the home app. There is no problem here since I use the cool status all the time, never auto so if I only use the home app to control the AC it will always turn back on in cool status.

Scenario 2: if I as Siri either on my iPhone, HomePod, or anywhere else to "turn the office AC on" it will turn it on but in AUTO mode regardless of which state it was before. this is an issue since I have several HomePods around the house and I use them to ask Siri to turn on or off the AC in that specific room.

The only way I can use Siri and have the AC in cool mode is to specifically ask "hey Siri set the office AC to cool" and then it will turn on in cool mode.

also I have to call out that this is a new behavior, in the past when I asked Siri to "turn on the AC on in (whatever room) it will always turn it on in cool mode, not sure is this change was on apple side or homebridge or anything on the plugin changed.

anyways it will be good to go back to a default cool state regardless of which route you use to ask (Siri, Home App, Etc)

let me know if you want to run any other tests

**Comment by nitaybz** [comment]
unfortunately I cannot control what commands siri sends... If it changed by apple (nothing that I did in the plugin), there is nothing I can do about it... I can suggest 2 workarounds:
1. Create a scene with the name "Turn ON the Bedroom AC" and customize exactly how you want it to be turned on.
2. Change your request by saying: "Cool the room", "set AC to cool mode", "Set AC to x degrees"

**Comment by nitaybz** [comment]
Closing if you don't have anymore questions... feel free to reopen otherwise
