### ISSUE TITLE
Temp setting in auto mode

### ISSUE THREAD

**Issue by johncap523** [nitaybz/homebridge-sensibo-ac#79]
The plug-in doesn’t work right for auto mode. It lets you initially select your heat and cool set point but when you use it in a Scene both heat and cool go to the cool setting. I was using it as my setback, so heat was 67, and cool was 75. It sets both heat or cool to 75 and shows it that way.

**Comment by benwebbbenwebb** [comment]
Hi @johncap523 

While I understand what your suggesting (and how it's shown in the Home app) that unfortunately sounds more like a thermostat, rather than an AC, and it's not how the Sensibo API works.

It might depend on the unit, though for my two AC unit remotes (not Sensibo, actual remote) when set to AUTO they don't let me set a temperature range, just a single temperature. Sensibo works much the same for AUTO mode.

Best I can recommend is that you take a look at the `ClimateReact` mode within the Sensibo app. For my unit and model you can set a start and stop trigger. Once you've set it up in the Sensibo app the first time you can then set `"enableClimateReactSwitch": true` in Homebridge and turn it on/off from the Home app.
