### ISSUE TITLE
Feature request | Disable auto mode

### ISSUE THREAD

**Issue by avielc** [nitaybz/homebridge-sensibo-ac#91]
Hi all
For some reason lately the A/C is going directly into Auto mode - which usually doesn't cool, and just work as fan or heat. (which is horrible)
Can we please add some feature to allow disabling that option? (maybe even allow disabling any function unnecessary to individuals (e.g. I like A/C to cool only, no need for any other functions)

Thank you!

**Comment by Olivierbkk** [comment]
Hello,
I live in a tropical country and our aircon does not have heating as you can imagine. so on top of being able to disable the auto mode it would be nice to also be able to disable the heat mode, basically leaving the OFF and COOL. I am also not sure if that is possible but it would be good to have the option to separate the fan slider to a different tile to use automation only on the fan power.
thanks!

**Comment by benwebbbenwebb** [comment]
Hello @avielc and @Olivierbkk 

In the latest alpha version that I released today I've included a new `modesToExclude` setting. This should allow users to hide selected modes.

First, upgrade to the alpha by clicking the wrench icon on this plugin in the Plugins tab of Homebridge and select 'Install Alternate Version'.

Once installed you can either use the built-in Homebridge plugin settings config menu: go to the Plugins tab again and then click 'Settings' on this plugin, then scroll to the bottom _OR_ add the `modesToExclude` manually in the Config.json

Example:
"modesToExclude": ["MODE_TO_HIDE","ANOTHER_MODE_TO_HIDE"]

Valid values are: AUTO, COOL, DRY, FAN or HEAT. Select all that you want _removed_.

Note due to Apple Home app caching you will probably need to remove the AC unit from the Homebridge cache for the mode to full disappear. Details on how to do this here: https://github.com/nitaybz/homebridge-sensibo-ac/blob/development/README.md#troubleshooting-and-debug

Will be great to get your feedback on this and if it works for you.

**Comment by Olivierbkk** [comment]
Thank, I am trying that now
just one question, if I remove the AC from the homebridge cache, will I loose the automations associated to that device in HK?

**Comment by Olivierbkk** [comment]
The install crashes, I can't install the alpha version

**Comment by benwebbbenwebb** [comment]
Hi @Olivierbkk 

Yes, removing the AC from the cache may negatively impact your automations unfortunately... there's a chance they won't be if the name doesn't change etc, but I expect in many cases you'll need to re-add the unit.

As for the install crashing... that's unexpected! Is there any error message shown? I am successfully able to move between release (v2.3.4-release) and alpha (v2.4.0-alpha.3) versions in my personal Homebridge (v1.6.0) install running on a Pi 4, with Node.js Version v16.19.1.

Also, double checking you've ready tried the usual recommendations of restarting the computer that runs Homebridge, making sure the base Homebridge package is up to date etc?

**Comment by Olivierbkk** [comment]
too late I already lost all my automations somehow...

the install screen gets stuck on this
![Screen Shot 2023-04-03 at 19 25 49](https://user-images.githubusercontent.com/113991249/229508996-83db9d5d-5e8a-4d50-8b9c-e535d577be50.png)

I am using an old Raspberry Pi 1, model B rev 2.0
hb is up to date, i restarted etc... the basics

**Comment by Olivierbkk** [comment]
something came up after I tried several time, see below image
![image](https://user-images.githubusercontent.com/113991249/229512528-eb431c96-d0ec-4657-b6a7-03fe82b1c9c0.png)
see log file attached
[log.txt](https://github.com/nitaybz/homebridge-sensibo-ac/files/11138396/log.txt)

**Comment by benwebbbenwebb** [comment]
Thanks for providing the log file, I'll take a look tomorrow but at first glance strangely it seems to have received a process termination (SIGTERM) in the middle of performing NPM CLI actions (arborist I think?).

Not sure if this is due to a timeout or something...

I noted that some of the dependency downloads and reifyNode steps take quite a while, for example Google APIs (required by Fakegato) took over 1 minute to 'download' (re-validate from cache) and then over 13 minutes to 'reify' (not clear on what that step does).

Guessing the slowness is because it's a Raspberry Pi 1, my Pi Pico can be quite slow too (I use a Pi4 for Homebridge though). Is it taking 15+ minutes at your end and then hanging?

Out of interest, I didn't think Node 18 worked on older Raspberry Pi's, how did you get that working?

**Comment by Olivierbkk** [comment]
> Is it taking 15+ minutes at your end and then hanging?

yes I get the error message after about that time

> Out of interest, I didn't think Node 18 worked on older Raspberry Pi's, how did you get that working?

Sorry I do not remember exactly how I did it but it definitely did not work first time, I tried several things including update, upgrade and also `sudo apt --fix-broken install` if i'm not mistaken and after several reboots it did work out of the blue. Things are working normally since then so I guess I got it right to some extents. When I try `sudo apt upgrade` though I still get some error messages related to locked dpkg or something like that, not sure it's related.

**Comment by benwebbbenwebb** [comment]
Hi @Olivierbkk 

I’ve been thinking about your installation issue some more and wonder if a clean install of the plugin would help? You’d likely lose any existing AC units (and their scenes and settings) in both Homebridge and the Apple Home app though unfortunately.

I also read about some other npm flags that can be set to change timeouts and/or reduce steps that are run during NPM install, but not sure how far down that rabbit hole you want to go (and it is outside of the purview of this plugin and issue)

**Comment by Olivierbkk** [comment]
i tried clean install, still can't install

franly speaking I am not so much of a tinkerer, I try things without really knowing what I'm doing so I don't mind to try things but I would need some help as to what to do

**Comment by seidnerj** [comment]
Would love to see this feature as well.

**Comment by seidnerj** [comment]
I ended up simply adding the below in unified.js, immediately after `const mode = key.toUpperCase()`:

```
			if (mode === 'AUTO') {
				continue;
			}

```

I then removed the AC accessories via the Home app and then re-added them and voila, the Auto mode is gone.

**Comment by benwebbbenwebb** [comment]
> Would love to see this feature as well.

Hi @seidnerj 

You can try the alpha if you’d like, see my comment above https://github.com/nitaybz/homebridge-sensibo-ac/issues/91#issuecomment-1493992137

**Comment by benwebbbenwebb** [comment]
Closing as v2.5.0 now released and has modesToExclude - see [README.md - Disabling AC modes](https://github.com/nitaybz/homebridge-sensibo-ac/blob/v2.5.0/README.md#disabling-ac-modes) for more details.
